### ISSUE TITLE
Does not autocomplete iron

### ISSUE THREAD

**Issue by Emilgardis** [racer-rust/racer#528] opened 2016-04-10 17:45 UTC
Currently racer fails to autocomplete iron, no clue why.
[Gist](https://gist.github.com/Emilgardis/65b72030cc6718364cd08d460301edb2) for all related files.
#499 may be related.

**Comment by lem0nify** [comment] 2016-06-27 14:47
@Emilgardis It does. It just can't parse imports when you write `use module::something::*;` such as `use iron::prelude::*;`. So, if you will import symbols manually like `use iron::Iron;`, it will AC fine.

**Comment by TedDriggs** [comment] 2017-06-13 20:44
This looks to be a duplicate of #499, unless I'm missing something. Closing this to focus the discussion there.

**Closed by TedDriggs** 2017-06-13 20:44 UTC
