### ISSUE TITLE
`cargo +nightly build --release` fails on Windows 10 (both on latest and v2.1.36)

### ISSUE THREAD

**Issue by lm-w1n5t0n** [racer-rust/racer#1158] opened 2021-02-06 15:37 UTC
Following the instructions on the README, I ran the following commands:

1. `rustup toolchain add nightly`
    <details>
    <summary>output</summary>
  
    ```
    info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
    info: latest update on 2021-02-06, rust version 1.51.0-nightly (23adf9fd8 2021-02-05)
    info: skipping nightly which is missing installed component 'rustfmt'
    info: syncing channel updates for 'nightly-2021-02-05-x86_64-pc-windows-msvc'
    info: latest update on 2021-02-05, rust version 1.51.0-nightly (4f4656d46 2021-02-04)
    info: skipping nightly which is missing installed component 'rustfmt'
    info: syncing channel updates for 'nightly-2021-02-04-x86_64-pc-windows-msvc'
    info: latest update on 2021-02-04, rust version 1.51.0-nightly (e708cbd91 2021-02-03)
    info: skipping nightly which is missing installed component 'rustfmt'
    info: syncing channel updates for 'nightly-2021-02-03-x86_64-pc-windows-msvc'
    info: latest update on 2021-02-03, rust version 1.51.0-nightly (368275062 2021-02-02)
    info: skipping nightly which is missing installed component 'rustfmt'
    info: syncing channel updates for 'nightly-2021-02-02-x86_64-pc-windows-msvc'
    info: latest update on 2021-02-02, rust version 1.51.0-nightly (d4e3570db 2021-02-01)
    info: skipping nightly which is missing installed component 'rustfmt'
    info: syncing channel updates for 'nightly-2021-02-01-x86_64-pc-windows-msvc'
    info: latest update on 2021-02-01, rust version 1.51.0-nightly (0e63af5da 2021-01-31)
    info: skipping nightly which is missing installed component 'rustfmt'
    info: syncing channel updates for 'nightly-2021-01-31-x86_64-pc-windows-msvc'
    info: latest update on 2021-01-31, rust version 1.51.0-nightly (04caa632d 2021-01-30)
    info: downloading component 'cargo'
    info: downloading component 'clippy'
    info: downloading component 'rust-docs'
    info: downloading component 'rust-std'
    info: downloading component 'rustc'
    info: downloading component 'rustfmt'
    info: installing component 'cargo'
    info: using up to 500.0 MiB of RAM to unpack components
    info: installing component 'clippy'
    info: installing component 'rust-docs'
    info: installing component 'rust-std'
    info: installing component 'rustc'
    info: installing component 'rustfmt'
    
      nightly-x86_64-pc-windows-msvc installed - rustc 1.51.0-nightly (04caa632d 2021-01-30)
    
    info: checking for self-updates
    ```
    </details>

2. `git clone https://github.com/racer-rust/racer.git && cd racer`
3. `cargo +nightly build --release`

    <details>
      <summary>output</summary>
      
    ```
     Downloading crates ...
      Downloaded aho-corasick v0.7.10
      Downloaded getrandom v0.1.14
      Downloaded autocfg v1.0.0
      Downloaded lazycell v1.2.1
      Downloaded indexmap v1.5.2
      Downloaded memchr v2.3.3
      Downloaded rand v0.7.3
      Downloaded rls-span v0.5.2
      Downloaded remove_dir_all v0.5.2
      Downloaded stable_deref_trait v1.1.1
      Downloaded smallvec v1.4.2
      Downloaded quote v1.0.3
      Downloaded tracing-attributes v0.1.11
      Downloaded tracing v0.1.19
      Downloaded log v0.4.8
      Downloaded derive_more v0.99.5
      Downloaded memoffset v0.5.4
      Downloaded ppv-lite86 v0.2.6
      Downloaded lock_api v0.4.1
      Downloaded clap v2.33.0
      Downloaded serde_derive v1.0.105
      Downloaded termcolor v1.1.0
      Downloaded tempfile v3.1.0
      Downloaded vec_map v0.8.1
      Downloaded unicode-xid v0.2.0
      Downloaded serde v1.0.105
      Downloaded instant v0.1.7
      Downloaded proc-macro2 v1.0.10
      Downloaded ryu v1.0.3
      Downloaded serde_json v1.0.50
      Downloaded arrayvec v0.5.1
      Downloaded either v1.5.3
      Downloaded hashbrown v0.8.2
      Downloaded rand_chacha v0.2.2
      Downloaded stacker v0.1.12
      Downloaded sha2 v0.9.2
      Downloaded num_cpus v1.12.0
      Downloaded winapi-util v0.1.4
      Downloaded rand_core v0.5.1
      Downloaded winapi v0.3.8
      Downloaded parking_lot_core v0.8.0
      Downloaded libc v0.2.77
      Downloaded unicode-width v0.1.7
      Downloaded regex-syntax v0.6.17
      Downloaded thread_local v1.0.1
      Downloaded tracing-core v0.1.15
      Downloaded parking_lot v0.11.0
      Downloaded psm v0.1.8
      Downloaded synstructure v0.12.3
      Downloaded cc v1.0.53
      Downloaded humantime v2.0.0
      Downloaded unicode-normalization v0.1.12
      Downloaded regex v1.3.6
      Downloaded sha-1 v0.9.2
      Downloaded syn v1.0.17
      Downloaded itoa v0.4.5
       Compiling cfg-if v0.1.10
       Compiling autocfg v1.0.0
       Compiling proc-macro2 v1.0.10
       Compiling unicode-xid v0.2.0
       Compiling winapi v0.3.8
       Compiling syn v1.0.17
       Compiling lazy_static v1.4.0
       Compiling scopeguard v1.1.0
       Compiling typenum v1.12.0
       Compiling smallvec v1.4.2
       Compiling version_check v0.9.2
       Compiling getrandom v0.1.14
       Compiling cc v1.0.53
       Compiling libc v0.2.77
       Compiling maybe-uninit v2.0.0
       Compiling log v0.4.8
       Compiling ppv-lite86 v0.2.6
       Compiling bitflags v1.2.1
       Compiling rustc-rayon-core v0.3.0
       Compiling opaque-debug v0.3.0
       Compiling unicode-width v0.1.7
       Compiling cfg-if v1.0.0
       Compiling either v1.5.3
       Compiling arrayvec v0.5.1
       Compiling rustc-hash v1.1.0
       Compiling cpuid-bool v0.1.2
       Compiling stable_deref_trait v1.1.1
       Compiling rustc-ap-rustc_graphviz v702.0.0
       Compiling jobserver v0.1.21
       Compiling scoped-tls v1.0.0
       Compiling serde v1.0.105
       Compiling memchr v2.3.3
       Compiling ryu v1.0.3
       Compiling annotate-snippets v0.8.0
       Compiling rustc-ap-rustc_fs_util v702.0.0
       Compiling regex-syntax v0.6.17
       Compiling itoa v0.4.5
       Compiling quick-error v1.2.3
       Compiling strsim v0.8.0
       Compiling vec_map v0.8.1
       Compiling humantime v2.0.0
       Compiling lazycell v1.2.1
       Compiling instant v0.1.7
       Compiling lock_api v0.4.1
       Compiling crossbeam-utils v0.6.6
       Compiling tracing-core v0.1.15
       Compiling thread_local v1.0.1
       Compiling rustc-ap-rustc_arena v702.0.0
    error[E0658]: use of unstable library feature 'array_value_iter'
       --> C:\Users\Scored\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc-ap-rustc_arena-702.0.0\src\lib.rs:134:40
        |
    134 | impl<T, const N: usize> IterExt<T> for std::array::IntoIter<T, N> {
        |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
        |
        = note: see issue #65798 <https://github.com/rust-lang/rust/issues/65798> for more information
        = help: add `#![feature(array_value_iter)]` to the crate attributes to enable
    
    error[E0658]: use of unstable library feature 'array_value_iter_slice'
       --> C:\Users\Scored\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc-ap-rustc_arena-702.0.0\src\lib.rs:144:18
        |
    144 |             self.as_slice().as_ptr().copy_to_nonoverlapping(start_ptr, len);
        |                  ^^^^^^^^
        |
        = note: see issue #65798 <https://github.com/rust-lang/rust/issues/65798> for more information
        = help: add `#![feature(array_value_iter_slice)]` to the crate attributes to enable
    
    error: aborting due to 2 previous errors
    
    For more information about this error, try `rustc --explain E0658`.
    error: could not compile `rustc-ap-rustc_arena`
    
    To learn more, run the command again with --verbose.
    warning: build failed, waiting for other jobs to finish...
    error: build failed
    ```
    </details>

4. That failed, so I tried checking the latest release commit: 
    `git checkout 94929a2f0b662465601abbd686bf080252e76009`

    <details>
      <summary>output</summary>
      
    ```
    Note: switching to '94929a2f0b662465601abbd686bf080252e76009'.
    
    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by switching back to a branch.
    
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -c with the switch command. Example:
    
      git switch -c <new-branch-name>
    
    Or undo this operation with:
    
      git switch -
    
    Turn off this advice by setting config variable advice.detachedHead to false
    
    HEAD is now at 94929a2 Bump version to 2.1.36
    ```
    </details>

5. `cargo +nightly build --release`

    <details>
      <summary>output</summary>
      
    ```
     Downloading crates ...
      Downloaded block-buffer v0.7.3
      Downloaded block-padding v0.1.5
      Downloaded byte-tools v0.3.1
      Downloaded generic-array v0.12.3
      Downloaded fake-simd v0.1.2
      Downloaded once_cell v1.4.0
      Downloaded parking_lot v0.10.2
      Downloaded rustc-ap-rustc_ast_pretty v669.0.0
      Downloaded smallvec v0.6.13
      Downloaded rustc-ap-rustc_graphviz v669.0.0
      Downloaded indexmap v1.3.2
      Downloaded memmap v0.7.0
      Downloaded md-5 v0.8.0
      Downloaded rustc-ap-rustc_ast v669.0.0
      Downloaded rustc-ap-rustc_data_structures v669.0.0
      Downloaded measureme v0.7.1
      Downloaded libc v0.2.68
      Downloaded rustc-ap-rustc_fs_util v669.0.0
      Downloaded rustc-ap-rustc_arena v669.0.0
      Downloaded sha-1 v0.8.2
      Downloaded semver v0.9.0
      Downloaded digest v0.8.1
      Downloaded parking_lot_core v0.6.2
      Downloaded rustc-ap-rustc_session v669.0.0
      Downloaded semver-parser v0.7.0
      Downloaded smallvec v1.2.0
      Downloaded parking_lot v0.9.0
      Downloaded opaque-debug v0.2.3
      Downloaded parking_lot_core v0.7.2
      Downloaded rustc-ap-rustc_serialize v669.0.0
      Downloaded byteorder v1.3.4
      Downloaded rustc-ap-rustc_span v669.0.0
      Downloaded rustc-ap-rustc_feature v669.0.0
      Downloaded stacker v0.1.9
      Downloaded rustc-ap-rustc_index v669.0.0
      Downloaded rustc_version v0.2.3
      Downloaded rustc-ap-rustc_macros v669.0.0
      Downloaded rustc-ap-rustc_errors v669.0.0
      Downloaded rustc-ap-rustc_lexer v669.0.0
      Downloaded lock_api v0.3.4
      Downloaded rustc-ap-rustc_parse v669.0.0
      Downloaded rustc-ap-rustc_target v669.0.0
       Compiling winapi v0.3.8
       Compiling semver-parser v0.7.0
       Compiling syn v1.0.17
       Compiling byteorder v1.3.4
       Compiling smallvec v1.2.0
       Compiling libc v0.2.68
       Compiling byte-tools v0.3.1
       Compiling rustc-ap-rustc_graphviz v669.0.0
       Compiling opaque-debug v0.2.3
       Compiling fake-simd v0.1.2
       Compiling rustc-ap-rustc_ast v669.0.0
       Compiling rustc-ap-rustc_target v669.0.0
       Compiling rustc-ap-rustc_fs_util v669.0.0
       Compiling memoffset v0.5.4
       Compiling crossbeam-utils v0.7.2
       Compiling crossbeam-epoch v0.8.2
       Compiling indexmap v1.3.2
       Compiling proc-macro2 v1.0.10
       Compiling maybe-uninit v2.0.0
       Compiling lock_api v0.3.4
       Compiling psm v0.1.8
       Compiling stacker v0.1.9
       Compiling typenum v1.12.0
       Compiling log v0.4.8
       Compiling rustc-rayon-core v0.3.0
       Compiling bitflags v1.2.1
       Compiling getopts v0.2.21
       Compiling textwrap v0.11.0
       Compiling serde v1.0.105
       Compiling memchr v2.3.3
       Compiling rustc-ap-rustc_lexer v669.0.0
       Compiling block-padding v0.1.5
       Compiling ryu v1.0.3
       Compiling humantime v1.3.0
       Compiling semver v0.9.0
       Compiling unicode-normalization v0.1.12
       Compiling crossbeam-queue v0.1.2
       Compiling rustc_version v0.2.3
       Compiling smallvec v0.6.13
       Compiling ena v0.14.0
       Compiling quote v1.0.3
       Compiling aho-corasick v0.7.10
       Compiling num_cpus v1.12.0
       Compiling generic-array v0.12.3
       Compiling parking_lot_core v0.6.2
       Compiling parking_lot v0.9.0
       Compiling rustc-ap-rustc_serialize v669.0.0
       Compiling block-buffer v0.7.3
       Compiling digest v0.8.1
       Compiling sha-1 v0.8.2
       Compiling md-5 v0.8.0
       Compiling crossbeam-deque v0.7.3
       Compiling regex v1.3.6
       Compiling rustc-rayon v0.3.0
       Compiling rustc-ap-rustc_index v669.0.0
       Compiling parking_lot_core v0.7.2
       Compiling memmap v0.7.0
       Compiling atty v0.2.14
       Compiling winapi-util v0.1.4
       Compiling termize v0.1.1
       Compiling parking_lot v0.10.2
       Compiling clap v2.33.0
       Compiling termcolor v1.1.0
       Compiling once_cell v1.4.0
       Compiling measureme v0.7.1
       Compiling env_logger v0.7.1
       Compiling rustc-ap-rustc_data_structures v669.0.0
    error[E0557]: feature has been removed
      --> C:\Users\Scored\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc-ap-rustc_data_structures-669.0.0\lib.rs:16:12
       |
    16 | #![feature(optin_builtin_traits)]
       |            ^^^^^^^^^^^^^^^^^^^^ feature has been removed
       |
       = note: renamed to `auto_traits`
    
    error[E0658]: auto traits are experimental and possibly buggy
      --> C:\Users\Scored\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc-ap-rustc_data_structures-669.0.0\sync.rs:30:9
       |
    30 |         pub auto trait Send {}
       |         ^^^^^^^^^^^^^^^^^^^^^^
       |
       = note: see issue #13231 <https://github.com/rust-lang/rust/issues/13231> for more information
       = help: add `#![feature(auto_traits)]` to the crate attributes to enable
    
    error[E0658]: auto traits are experimental and possibly buggy
      --> C:\Users\Scored\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc-ap-rustc_data_structures-669.0.0\sync.rs:31:9
       |
    31 |         pub auto trait Sync {}
       |         ^^^^^^^^^^^^^^^^^^^^^^
       |
       = note: see issue #13231 <https://github.com/rust-lang/rust/issues/13231> for more information
       = help: add `#![feature(auto_traits)]` to the crate attributes to enable
    
       Compiling synstructure v0.12.3
    error: aborting due to 3 previous errors
    
    Some errors have detailed explanations: E0557, E0658.
    For more information about an error, try `rustc --explain E0557`.
    error: could not compile `rustc-ap-rustc_data_structures`
    
    To learn more, run the command again with --verbose.
    warning: build failed, waiting for other jobs to finish...
    error: build failed
    ```
    </details>

**Comment by quadroli** [comment] 2021-02-06 16:54
@lm-w1n5t0n  brawskii, i have found the solution!
simply uninstall rust 'rustup self uninstall'
reinstall it 'curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh'
clone the repo 'git clone https://github.com/racer-rust/racer.git'
cd into it 'cd racer'
then finally run 'cargo build --release'

worked a 100 persento for me baguette_bread man_artist

**Comment by calebcartwright** [comment] 2021-02-06 21:59
Duplicate of #1154

Note that rustup skips pulling newer nightlies that missing installed components and falls back to previous releases, so you need to include `--force` when running update. There were also some subsequent upstream changes in the rustc crates that cause issues on the latest nightly (will be resolved by #1159), but latest on master should build with `nightly-2021-02-03`

**Comment by koalazub** [comment] 2021-02-09 06:15
Just tried installing again today and I'm still unable to do so via `rustup update`

**Comment by quadroli** [comment] 2021-02-12 16:59
@koalazub brawskiiiii, did you follow the guide i provided?

**Comment by koalazub** [comment] 2021-02-15 01:42
@quadroli I have not, but I'll give it a shot right after work. Cheers for sharing the trick mate!

**Closed** 2021-05-03 20:13 UTC
