### ISSUE TITLE
racer does not offer completions after `?` operator

### ISSUE THREAD

**Issue by mqudsi** [racer-rust/racer#766] opened 2017-07-19 04:33 UTC
With the testcase.rs containing the following:

```rust
use std::fs::File;
use std::io::{Read, Write};

use std::path::Path;

fn main() {
    test();
}

fn test() -> std::io::Result<()> {
    let src = File::open("test.doc")?;
    src.

    return Ok(());
}
```

Executing `racer complete 12 8 testcase.rs` results in the following;

```
PREFIX 179,179,
END
```

Whereas directly unwrapping the result of the IO operation causes racer to provide suggestions normally:

```rust
use std::fs::File;
use std::io::{Read, Write};

use std::path::Path;

fn main() {
    test();
}

fn test() -> std::io::Result<()> {
    let src = File::open("test.doc").unwrap();
    src.

    return Ok(());
}
```

and executing `racer complete 12 8 src/testcase.rs` results in the following:

```
PREFIX 187,187,
MATCH inner,88,4,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,StructField,fs_imp::File
MATCH sync_all,283,11,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,pub fn sync_all(&self) -> io::Result<()>
MATCH sync_data,314,11,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,pub fn sync_data(&self) -> io::Result<()>
MATCH set_len,342,11,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,pub fn set_len(&self, size: u64) -> io::Result<()>
MATCH metadata,360,11,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,pub fn metadata(&self) -> io::Result<Metadata>
MATCH try_clone,382,11,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,pub fn try_clone(&self) -> io::Result<File>
MATCH set_permissions,418,11,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,pub fn set_permissions(&self, perm: Permissions) -> io::Result<()>
MATCH as_inner,424,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,fn as_inner(&self) -> &fs_imp::File
MATCH as_inner,63,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/sys_common/mod.rs,Function,fn as_inner(&self) -> &Inner
MATCH into_inner,432,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,fn into_inner(self) -> fs_imp::File
MATCH into_inner,75,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/sys_common/mod.rs,Function,fn into_inner(self) -> Inner
MATCH fmt,439,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result
MATCH fmt,513,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/../liballoc/../libcore/fmt/mod.rs,Function,fn fmt(&self, f: &mut Formatter) -> Result
MATCH read,446,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,fn read(&mut self, buf: &mut [u8]) -> io::Result<usize>
MATCH initializer,451,14,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,unsafe fn initializer(&self) -> Initializer
MATCH read,503,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn read(&mut self, buf: &mut [u8]) -> Result<usize>
MATCH initializer,526,14,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,unsafe fn initializer(&self) -> Initializer
MATCH read_to_end,570,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn read_to_end(&mut self, buf: &mut Vec<u8>) -> Result<usize>
MATCH read_to_string,608,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn read_to_string(&mut self, buf: &mut String) -> Result<usize>
MATCH read_exact,669,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn read_exact(&mut self, mut buf: &mut [u8]) -> Result<()>
MATCH by_ref,721,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn by_ref(&mut self) -> &mut Self where Self: Sized
MATCH bytes,751,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn bytes(self) -> Bytes<Self> where Self: Sized
MATCH chars,791,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn chars(self) -> Chars<Self> where Self: Sized
MATCH chain,826,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn chain<R: Read>(self, next: R) -> Chain<Self, R> where Self: Sized
MATCH take,860,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn take(self, limit: u64) -> Take<Self> where Self: Sized
MATCH write,457,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,fn write(&mut self, buf: &[u8]) -> io::Result<usize>
MATCH flush,460,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,fn flush(&mut self) -> io::Result<()>
MATCH write,988,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn write(&mut self, buf: &[u8]) -> Result<usize>
MATCH flush,1014,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn flush(&mut self) -> Result<()>
MATCH write_all,1044,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn write_all(&mut self, mut buf: &[u8]) -> Result<()>
MATCH write_fmt,1096,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn write_fmt(&mut self, fmt: fmt::Arguments) -> Result<()>
MATCH by_ref,1152,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn by_ref(&mut self) -> &mut Self where Self: Sized
MATCH seek,464,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,fn seek(&mut self, pos: SeekFrom) -> io::Result<u64>
MATCH seek,1198,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn seek(&mut self, pos: SeekFrom) -> Result<u64>
MATCH read,470,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,fn read(&mut self, buf: &mut [u8]) -> io::Result<usize>
MATCH initializer,475,14,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,unsafe fn initializer(&self) -> Initializer
MATCH read,503,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn read(&mut self, buf: &mut [u8]) -> Result<usize>
MATCH initializer,526,14,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,unsafe fn initializer(&self) -> Initializer
MATCH read_to_end,570,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn read_to_end(&mut self, buf: &mut Vec<u8>) -> Result<usize>
MATCH read_to_string,608,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn read_to_string(&mut self, buf: &mut String) -> Result<usize>
MATCH read_exact,669,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn read_exact(&mut self, mut buf: &mut [u8]) -> Result<()>
MATCH by_ref,721,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn by_ref(&mut self) -> &mut Self where Self: Sized
MATCH bytes,751,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn bytes(self) -> Bytes<Self> where Self: Sized
MATCH chars,791,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn chars(self) -> Chars<Self> where Self: Sized
MATCH chain,826,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn chain<R: Read>(self, next: R) -> Chain<Self, R> where Self: Sized
MATCH take,860,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn take(self, limit: u64) -> Take<Self> where Self: Sized
MATCH write,481,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,fn write(&mut self, buf: &[u8]) -> io::Result<usize>
MATCH flush,484,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,fn flush(&mut self) -> io::Result<()>
MATCH write,988,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn write(&mut self, buf: &[u8]) -> Result<usize>
MATCH flush,1014,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn flush(&mut self) -> Result<()>
MATCH write_all,1044,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn write_all(&mut self, mut buf: &[u8]) -> Result<()>
MATCH write_fmt,1096,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn write_fmt(&mut self, fmt: fmt::Arguments) -> Result<()>
MATCH by_ref,1152,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn by_ref(&mut self) -> &mut Self where Self: Sized
MATCH seek,488,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/fs.rs,Function,fn seek(&mut self, pos: SeekFrom) -> io::Result<u64>
MATCH seek,1198,7,/mnt/c/Users/Mahmoud/git/rust/src/libstd/io/mod.rs,Function,fn seek(&mut self, pos: SeekFrom) -> Result<u64>
END
```

**Comment by TedDriggs** [comment] 2017-07-19 15:03
Duplicate of #743

**Closed by TedDriggs** 2017-07-19 15:03 UTC

**Comment by mqudsi** [comment] 2017-07-19 15:19
Thanks. Sorry about that, I tried searching before posting but I guess I didn't do that good of a job :)
