### ISSUE TITLE
extern functions are ignored

### ISSUE THREAD

**Issue by Wilfred** [racer-rust/racer#678] opened 2017-01-03 22:26 UTC
I can find the definition of `foo` in this case:

```rust
pub fn foo() {}

fn bar() {
    foo();
}
```

However, if my function is `extern "C"`:

```rust
pub extern "C" fn foo() {}

fn bar() {
    foo();
}
```

Racer only returns `END`:

```
$ RUST_SRC_PATH=/home/wilfred/src/rustc-1.10.0/src racer find-definition 4 4 foo.rs
END
```

**Comment by TedDriggs** [comment] 2017-06-13 20:35
This looks like a duplicate of #347

**Closed by TedDriggs** 2017-06-13 20:35 UTC
Labels: bug, duplicate
