### ISSUE TITLE
Racer discards blank lines in module docstrings

### ISSUE THREAD

**Issue by Wilfred** [racer-rust/racer#646] opened 2016-11-05 00:35 UTC
For example, given a file of the form:

```rust
std::result
```

```
$ CARGO_HOME=/home/wilfred/.cargo RUST_SRC_PATH=/home/wilfred/src/rustc-1.10.0/src /home/wilfred/.cargo/bin/racer complete-with-snippet 1 11 /home/wilfred/projects/bfc/src/foo.rs
PREFIX 5,11,result
MATCH result;result;1;0;/home/wilfred/src/rustc-1.10.0/src/libstd/../libcore/result.rs;Module;/home/wilfred/src/rustc-1.10.0/src/libstd/../libcore/result.rs;"Error handling with the `Result` type.\n`Result<T, E>` is the type used for returning and propagating\nerrors. It is an enum with the variants, `Ok(T)`, representing\nsuccess and containing a value, and `Err(E)`, representing error\nand containing an error value.\n```\n# #[allow(dead_code)]\nenum Result<T, E> {\n   Ok(T),\n   Err(E),\n}\n```\nFunctions return `Result` whenever errors are expected and\nrecoverable. In the `std` crate `Result` is most prominently used\nfor [I/O](../../std/io/index.html).\nA simple function returning `Result` might be\ndefined and used like so:\n```\n#[derive(Debug)]\nenum Version { Version1, Version2 }\nfn parse_version(header: &[u8]) ->
... truncated
```

The raw docstring says:

```
//! Error handling with the `Result` type.
//!
//! `Result<T, E>` is the type used for returning and propagating
//! errors. It is an enum with the variants, `Ok(T)`, representing
//! success and containing a value, and `Err(E)`, representing error
//! and containing an error value.
```

However, the blank line seems to be completely stripped from the racer output:

```
Error handling with the `Result` type.\n`Result<T, E>` is the type used for returning and propagating\nerrors.
```

**Comment by Wilfred** [comment] 2016-11-05 00:37
This seems to only occur for module docstrings, not for e.g. struct docstrings.

**Comment by TedDriggs** [comment] 2017-06-09 20:56
This seems like a duplicate of #683.

**Comment by TedDriggs** [comment] 2017-06-12 18:17
#684 has fixed this issue; it will be in the next release.

**Closed by TedDriggs** 2017-06-12 18:17 UTC
Labels: bug
