### ISSUE TITLE
No macro support at all?

### ISSUE THREAD

**Issue by mexus** [racer-rust/racer#760] opened 2017-07-14 20:26 UTC
Hi guys!
First of all thanks for such a crucial for the development tool, without it programming with Rust would be next to impossible.

I've got a question (an issue probably) about completion for results of macros though.
Here's a minimal example of what I'm talking about:
```rust
use std::result::Result;
fn test1() -> Result<String, ()> {
  Err(())
}
fn test2() -> Result<(), ()> {
  let text = try!(test1());
  text. // No completion happens here.
  ...
}
```

I've managed to find several threads (old ones though, like #387) but they aren't quite answering my question though.

It's very annoying :( During early development I usually just use the `unwrap()` method (and the completion works fine) but later on I replace everything with a proper error handling and the completion stops working.. unless I provide a full type specialization which I'd like to avoid.

Actually I'm creating the issue only because there is no issue for macro support in general. And I can't really call this -- #463 -- to be a "support" because IMO the general use case is for macros defined somewhere outside of a file that's being edited.

Thanks a lot!

**Comment by TedDriggs** [comment] 2017-07-14 21:10
This is a duplicate of #389; the title for that one wasn't very descriptive, so I've updated it to be more broad.

We do have support for seeing through the `?` operator (which is equivalent to `try!`), but that doesn't work when one of the type parameters in the `Result` is `()`. That was added in #726.

**Closed by TedDriggs** 2017-07-14 21:10 UTC

**Comment by mexus** [comment] 2017-07-14 21:25
Ok, thanks for the clarification!
