### ISSUE TITLE
No completion for third-party transitive dependencies

### ISSUE THREAD

**Issue by thekrampus** [racer-rust/racer#710] opened 2017-04-16 22:13 UTC
Hi, I've only just started using racer today and I'm very new to racer and rust in general. This might very well not be a bug, but a misconfiguration on my part. Thanks for the assistance in any case.

I'm using:
Arch Linux 4.10.9-1
`rustc -V` -> rustc 1.16.0
`cargo -V` -> cargo-0.17.0-dev (f9e54817 2017-03-03)
`racer -V` -> racer 2.0.6
`echo $CARGO_HOME` -> /home/rob/.cargo/
Rust, cargo, and racer were all installed through the arch package repos.

I noticed this problem with [piston](https://github.com/PistonDevelopers/piston). In my `Cargo.toml`:
```TOML
[dependencies]
piston = "0.31.4"
pistoncore-input = "0.17.1" # also provided by piston::input
```
I would expect that by simply including `piston`, racer would offer completions on `piston::input`. However, this is not the case:
```rust
extern crate piston;
extern crate input; // same as piston::input

use piston::input:: // no completions through racer
use input:: // correct completions as expected
```
Thanks again, and let me know if there's more information I should provide.

**Comment by TedDriggs** [comment] 2017-06-13 20:41
This looks to be a duplicate of #624.

**Closed by TedDriggs** 2017-06-13 20:41 UTC
Labels: duplicate
