### ISSUE TITLE
Can't find-definition for symbols in `include!(...)` files.

### ISSUE THREAD

**Issue by dpc** [racer-rust/racer#693] opened 2017-02-07 05:31 UTC
Quite often I use `include!(subfile.rs)` to break one module into separate pieces (yet still same namespace etc.).

However I've noticed that after doing so, I can no longer jump to symbols that I've moved.

**Comment by TedDriggs** [comment] 2017-06-09 19:37
Closing this as a duplicate of #191

**Closed by TedDriggs** 2017-06-09 19:37 UTC
Labels: duplicate
